### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by rmosleh** [m-d-grunnill/MetaCast#1]
Hi Martin,

I have some questions about your code, just for educating. Are you coming to the lab next Wednesday?

**Comment by m-d-grunnill** [comment]
Hey Rahele

I am assuming that is your username. I will not be becoming in, but I am free that day and can meet via zoom.

Yours Martin

**Comment by rmosleh** [comment]
Hi Martin,
Thank you for your reply.
Yes, the online meeting is a good idea. I am also free on Wednesday and we can make it whenever is convenient for both us.

I am looking forward to  hearing from you .

Have a great weekend,
Rahele

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
