### ISSUE TITLE
JOSS Review - Recommended Edits for Paper.md

### ISSUE THREAD

**Issue by acolum** [m-d-grunnill/MetaCast#3]
Hi @m-d-grunnill,

Overall, this paper looks good, but I noticed some grammatical and structural issues:
- Under **Summary**, on line 18, the comma after "models" should be moved to after "flexibly." Also, the acronym "ODE" should be defined before using it.
- Under **Statement of need**:
    - The third word in the title of this section should be capitalized to match the capitalization pattern shown in the other sections' titles.
    - On line 33: The word "to" should be added between "order" and "expedite."
    - On line 37: The phrase that starts with "The dimensions (groupings)..." is a fragment and should be merged with one of the sentences around it.
    - On line 37: The word "cluster" should be "clusters."
    - On lines 38-40: The sentence that starts with "MetaCast builds..." could be rewritten for greater clarity.
    - On lines 42-43: I'd suggest rewriting the phrase "makes MetaCast an ideal package" in the last sentence of this paragraph, as this phrase was already used in the last sentence of the paragraph right above it (under **Summary**). 
- Under **State of Field**:
     - On line 46: A comma should be added after "knowledge."
     - On lines 49 and 58: To stay consistent with previous descriptions of the package in the paper, the phrase "for Epidemiology" should be expanded to "for Epidemiology and Ecology." 
     - On line 60: `Covasim` should have the same formatting as `Epipack` and the other package names.
     - On line 61: The word "a" should be removed.
     - On line 67: The comma at the end of the line should be a colon.
- Under **Acknowledgements and Funding**, the bullet points are not rendering correctly in the PDF.

**Comment by robmoss** [comment]
Hi @m-d-grunnill, I have a few suggestions in addition to those above:

- Under **State of Field**:
  - On line 52: The word "a" should be removed from "Epimode [...] can also perform ~~a~~ sensitivity analyses on these pre-coded models".
  - On lines 53-54: The word "defining" could be removed from the sentence "[...] produce ODE models from ~~defining~~ transitions between", or replaced by "defined" (although I find that reads awkwardly).
  - On line 65: Consider rephrasing "Epimode [...] has agent based modelling", perhaps replacing "has" with "provides" or "implements".
  - On line 69: Similar to my previous suggestion, perhaps say "The Python package `Eir` (Jacob, 2021) **provides** epidemiological models [...]".

**Comment by m-d-grunnill** [comment]
These changes have been made to the paper.md file.
